platform :ios, '8.0'

target 'XujcClient' do
  pod 'UIColor-HexString'
  pod 'SSKeychain'
  pod 'MBProgressHUD'
  pod 'LMDropdownView'
  pod 'DZNEmptyDataSet'
  pod 'MMPopupView'
  pod 'MJRefresh'
  pod 'TTTAttributedLabel'

  # Core Frameworks
  pod 'Masonry'
  pod "AFNetworking", :git => 'https://github.com/luckytianyiyan/AFNetworking.git', :branch => 'ty_no_unescaped_ctrl_char'
  pod 'SDWebImage'

  # Services
  pod 'Instabug'
  pod 'AliyunOSSiOS', '~> 2.2.0'
  pod 'Google/Analytics'
end

target :XujcClientTests do
  pod 'Kiwi'
end

target :XujcClientTodayExtension do
  pod 'Masonry'
end

target :XujcClientCore do
  pod 'CupertinoYankee'
  pod 'ReactiveCocoa', '~> 2.5'
end

target :XujcEducationKit do
  pod 'FMDB'
end
