#!/bin/sh
current_dir=$(dirname $0)
target_dir=$current_dir/../XujcClient/XujcClient/Resource
convert $current_dir/../ImageSource/default_avatar.png -resize 'x500>' $target_dir/default_avatar@2x.png;
