#!/bin/sh
current_dir=$(dirname $0)
target_dir=$current_dir/../XujcClient/Resource/tabbar
for item in `find $current_dir/../ImageSource -name "tabbar-*.png" -maxdepth 1`;
do
  item_without_type=${item%.*}
  icon_2x=${item_without_type}"@2x.png"
  icon_3x=${item_without_type}"@3x.png"
  convert $item -resize 'x50>' $target_dir/${icon_2x##*/};
  convert $item -resize 'x75>' $target_dir/${icon_3x##*/};
  echo 'generate '${item}
done
